export type Order = {
    rowId: number;
    orderId: string;
    orderDate: Date;
    shipDate: Date;
    shipMode: string;
    customerId: string;
    customerName: string;
    segment: string;
    postalCode: string;
    city: string;
    state: string;
    country: string;
    region: string;
    market: string;
    productId: string;
    productName: string;
    subCategory: string;
    category: string;
    sales: number;
    quantity: number;
    discount: number;
    profit: number;
    shippingCost: number;
    orderPriority: string;
};
